title: Russ' Home Page
author: s061257
email: sater.rus@principal.com
description: > # this means to ignore newlines until "baseurl:"
  This is my home page. Not much to look at right now but I'm still learning!

# social links
twitter_username: your-twitter-handle
github_username:  s061257

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
